inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "config.ru"
    - "script/**/*"
    - "bin/{rails,rake,bundle}"
    - "Rakefile"
    - vendor/bundle/**/*

  inherit_mode:
    merge:
      - Exclude
