require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - "db/schema.*"
    - "db/migrate/*"
    - "config/**/*"
    - "config.ru"
    - "script/**/*"
    - "bin/{rails,rake,bundle}"
    - "Rakefile"
    - vendor/bundle/**/*

  inherit_mode:
    merge:
      - Exclude

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 6

RSpec/NestedGroups:
  Max: 4

Rails/LexicallyScopedActionFilter:
  Enabled: false

Metrics/MethodLength:
  Max: 20
