require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "config.ru"
    - "script/**/*"
    - "bin/{rails,rake,bundle}"
    - "Rakefile"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

Rails/LexicallyScopedActionFilter:
  Enabled: false
