services:
  db:
    container_name: postgres
    image: "postgres:latest"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    command: redis-server
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"

  sidekiq:
    container_name: sidekiq
    depends_on:
      - db
      - redis
      - web
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    secrets:
      - development_key
      - production_key

  web:
    container_name: web
    image: inicro-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    secrets:
      - development_key
      - production_key

volumes:
  postgres:
  redis:

secrets:
  development_key:
    file: ./config/credentials/development.key
  production_key:
    file: ./config/credentials/production.key
