default: &default
  adapter: postgresql
  username: postgres
  password: password
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: inicro_development

test:
  <<: *default
  database: inicro_testing

production:
  <<: *default
  username: <%= ENV["INICRO_PROD_USER"] %>
  password: <%= ENV["INICRO_PROD_PASSWORD"] %>
  host: <%= ENV["INICRO_PROD_HOST"] %>
  port: <%= ENV["INICRO_PROD_PORT"] %>
