default: &default
  adapter: postgresql
  username: postgres
  password: password
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: inicro_development

test:
  <<: *default
  database: inicro_testing

production:
  <<: *default
  username: <%= Rails.application.credentials.dig(:inicro_db, :user) %>
  password: <%= Rails.application.credentials.dig(:inicro_db, :password) %>
  host: <%= Rails.application.credentials.dig(:inicro_db, :host) %>
  port: <%= Rails.application.credentials.dig(:inicro_db, :port) %>
