default: &default
  adapter: postgresql
  username: inicro
  password: 15040mhs!
  encoding: unicode
  pool: 5
  timeout: 5000
  host: 127.0.0.1

development:
  <<: *default
  database: inicro_development

test:
  <<: *default
  database: inicro_testing
  username: inicro
  password: 15040mhs!
  host: 127.0.0.1

production:
  <<: *default
  username: <%= ENV["INICRO_PROD_USER"] %>
  password: <%= ENV["INICRO_PROD_PASSWORD"] %>
  host: <%= ENV["INICRO_PROD_HOST"] %>
  port: <%= ENV["INICRO_PROD_PORT"] %>
