name: Continuous integration
on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 15040mhs!
        ports: ["5432:5432"]
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql restart

      - name: Build and run test
        env:
          DATABASE_URL: postgres://postgres:15040mhs!@localhost:5432/inicro_testing
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 15040mhs!
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec
