name: Backend CI + Lint

on:
    push:
      branches:
        - main
        - develop
    pull_request:
      branches:
        - main
        - develop

jobs:
  test:
    name: Rspec Test & Code Coverage
    runs-on: ubuntu-latest
    needs: lint

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
          ports:
            - 5432:5432
          options:
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up environment variables for development
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          BASE_MAIL_SENDER: ${{ secrets.BASE_MAIL_SENDER }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          INICRO_PROD_USER: ${{ secrets.INICRO_PROD_USER }}
          INICRO_PROD_PASSWORD: ${{ secrets.INICRO_PROD_PASSWORD }}
          INICRO_PROD_HOST: ${{ secrets.INICRO_PROD_HOST }}
          INICRO_PROD_PORT: ${{ secrets.INICRO_PROD_PORT }}
        run: |
          # Command to set up environment variables

      - name: Install system dependencies
        run: |
          sudo apt-get -y update

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Install vips image variant
        run: |
          sudo apt-get install libvips

      - name: Database setup
        run: |
          bundle exec rails db:test:prepare db:migrate

      - name: RSpec tests
        run: |
          bundle exec rspec

      - name: Create code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/

  lint:
    name:  Linting and Security Audit
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Ruby
          uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
          with:
            bundler-cache: true
            ruby-version: 3.2.2

        - name: Install dependencies 
          run: |
            gem install bundler
            bundle install --jobs 4 --retry 3

        - name: Security audit dependencies
          run: bundle exec bundler-audit --update

        - name: Security audit application code
          run: bundle exec brakeman -q -w2

        - name: Lint via RuboCop
          run: bundle exec rubocop --parallel -A
