name: Maria 3333 333333 3456780

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Rspec Test Environment
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby 3.1.4
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1.4
          rubygems: latest

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Install system dependencies
        run: |
          sudo apt-get -y update
      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql restart

      - name: Log PostgreSQL server logs
        run: |
          sudo cat /var/log/postgresql/postgresql-14-main.log

      - name: RSpec tests
        env:
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/inicro_testing
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          INICRO_USER: ${{ secrets.POSTGRES_USER }}
          INICRO_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

        run: |
          bundle exec rspec
      - name: Create code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
